import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v16-appRouter';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ar" dir="rtl">
        {/*<dir lang="ar" dir="rtl">*/}
            <body>
            <AppRouterCacheProvider options={{ enableCssLayer: true }}>
                {children}
            </AppRouterCacheProvider>
            </body>
        {/*</dir>*/}
        </html>
    );
}
